State-management-refactor
concord-consortium/multidata-plugin pull request #42
Opened 2024-09-20 18:42 UTC by emcelroy

2024-09-24 19:35 UTC, scytacki requested changes
This looks really good to me. I left a couple comments about future improvements. 

I think the only thing that would be good to change in this PR is the duplicate code around creating the snapshot to send to `applySnapshot`.

2024-09-24 19:35 UTC, scytacki commented on src/hooks/useCodapState.tsx
> +    applySnapshot(collections, newCollectionModels);
This looks like the same code that is in `updateCollections`, can you consolidate it?

2024-09-24 20:27 UTC, emcelroy commented
> This looks really good to me. I left a couple comments about future improvements.
> 
> I think the only thing that would be good to change in this PR is the duplicate code around creating the snapshot to send to `applySnapshot`.

@scytacki  Thanks. I consolidated the duplicate code. I also had a go at updating the collections model like I think you were suggesting. Do those changes make sense? They appear to work fine, though I find the structure a little awkward. It seems a bit weird to have a `collectionsModel` with a `collections` property, but I couldn't think of a better way to do it.

2024-09-24 21:02 UTC, kswenson commented
> They appear to work fine, though I find the structure a little awkward. It seems a bit weird to have a `collectionsModel` with a `collections` property, but I couldn't think of a better way to do i

To be more analogous with CODAP itself, `collections` would be a property of the `DataSetModel`.

2024-09-25 18:48 UTC, emcelroy commented
> > They appear to work fine, though I find the structure a little awkward. It seems a bit weird to have a `collectionsModel` with a `collections` property, but I couldn't think of a better way to do i
> 
> To be more analogous with CODAP itself, `collections` would be a property of the `DataSetModel`.

@kswenson Thanks. That makes a lot of sense. I spent some time trying to make that work, but it doesn't seem as straightforward as you might expect, and it's still not clear to me how much more time it'd take to work that out. So I'd like to either stick with the current model changes or undo them and save that work for later like Scott originally suggested, if that sounds reasonable to you and @scytacki?

2024-09-25 19:34 UTC, scytacki approved these changes
This looks good to me. Yes I think it is fine to punt the renaming.

There might be some issues with the useEffect dependencies just including `collectionsModel`. However we can probably wait until we find a problem before addressing that.

2024-09-26 14:08 UTC, merged